export enum newsTypes {
  SET_NEWS = 'SET_NEWS',
  SET_POPULAR_NEWS = 'SET_POPULAR_NEWS',
  SET_NEWS_ERROR = 'SET_NEWS_ERROR',
  SET_POPULAR_NEWS_ERROR = 'SET_POPULAR_NEWS_ERROR',
  GET_ALL_NEWS = 'GET_ALL_NEWS'
}
